services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - fullstack-osa-13-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword

volumes:
  fullstack-osa-13-pgdata:
